name = "Jevo"
uuid = "3e78decc-cd14-43d0-8271-079b340fcef2"
authors = ["Jack <jackgarbus@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
